[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/shared/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://stripe-task-server-eta.vercel.app/:splat"
  status = 200
  force = true