[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  VITE_APP_URL = "${VITE_APP_URL}"
  STRIPE_SECRET_KEY = "${STRIPE_SECRET_KEY}"
  STRIPE_WEBHOOK_SECRET = "${STRIPE_WEBHOOK_SECRET}"
  FIREBASE_PROJECT_ID = "${FIREBASE_PROJECT_ID}"
  FIREBASE_PRIVATE_KEY = "${FIREBASE_PRIVATE_KEY}"
  FIREBASE_CLIENT_EMAIL = "${FIREBASE_CLIENT_EMAIL}"
  FIREBASE_CLIENT_ID = "${FIREBASE_CLIENT_ID}"
  FIREBASE_AUTH_URI = "${FIREBASE_AUTH_URI}"
  FIREBASE_TOKEN_URI = "${FIREBASE_TOKEN_URI}"
  FIREBASE_AUTH_PROVIDER_X509_CERT_URL = "${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}"
  FIREBASE_CLIENT_X509_CERT_URL = "${FIREBASE_CLIENT_X509_CERT_URL}"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://curious-cranachan-ab9992.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/shared/*"
  to = "/index.html"
  status = 200 
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

